// Package main Octane Sample Application
//
// This is the API for the Octane sample application.
//
// Swagger 2.0 Spec - generated by [go-swagger](https://github.com/go-swagger/go-swagger)
//
// Schemes: http
// Host: localhost:8080
// BasePath: /
// Version: 1.0
//
// Consumes:
// - application/json
//
// Produces:
// - application/json
//
// SecurityDefinitions:
// token:
//   type: apiKey
//   name: Authorization
//   in: header
//   description: "In the 'Value' textbox below, please enter in the word 'Bearer', a space, and then paste in your token."
//
// swagger:meta
package main

import "github.com/josephspurrier/octane/example/app/config"

func main() {
	// Load the application.
	e := config.Config()

	// Start server.
	e.Logger.Fatal(e.Start(":8080"))
}
